FROM mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye
RUN apt update
RUN npm install -g yarn
RUN yarn add webpack webpack-cli webpack-dev-server babel-loader @babel/core @babel/preset-env @babel/preset-react